import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "primary":                  "#855300",
        "on-primary":               "#ffffff",
        "primary-container":        "#f59e0b",
        "on-primary-container":     "#613b00",
        "primary-fixed":            "#ffddb8",
        "primary-fixed-dim":        "#ffb95f",
        "on-primary-fixed":         "#2a1700",
        "on-primary-fixed-variant": "#653e00",
        "inverse-primary":          "#ffb95f",
        "secondary":                "#006c49",
        "on-secondary":             "#ffffff",
        "secondary-container":      "#6cf8bb",
        "on-secondary-container":   "#00714d",
        "secondary-fixed":          "#6ffbbe",
        "secondary-fixed-dim":      "#4edea3",
        "on-secondary-fixed":       "#002113",
        "on-secondary-fixed-variant":"#005236",
        "tertiary":                 "#00658b",
        "on-tertiary":              "#ffffff",
        "tertiary-container":       "#1abdff",
        "on-tertiary-container":    "#004966",
        "tertiary-fixed":           "#c5e7ff",
        "tertiary-fixed-dim":       "#7fd0ff",
        "on-tertiary-fixed":        "#001e2d",
        "on-tertiary-fixed-variant":"#004c6a",
        "error":                    "#ba1a1a",
        "on-error":                 "#ffffff",
        "error-container":          "#ffdad6",
        "on-error-container":       "#93000a",
        "background":               "#fff8f4",
        "on-background":            "#221a12",
        "surface":                  "#fff8f4",
        "surface-dim":              "#e7d7c9",
        "surface-bright":           "#fff8f4",
        "surface-container-lowest": "#ffffff",
        "surface-container-low":    "#fff1e5",
        "surface-container":        "#fbebdd",
        "surface-container-high":   "#f5e6d7",
        "surface-container-highest":"#f0e0d1",
        "on-surface":               "#221a12",
        "on-surface-variant":       "#534434",
        "surface-variant":          "#f0e0d1",
        "outline":                  "#867461",
        "outline-variant":          "#d8c3ad",
        "inverse-surface":          "#382f25",
        "inverse-on-surface":       "#feeedf",
        "surface-tint":             "#855300",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        display:  ["Inter", "sans-serif"],
        body:     ["Inter", "sans-serif"],
        label:    ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg:      "0.5rem",
        xl:      "0.75rem",
        "2xl":   "1rem",
        full:    "9999px",
      },
    },
  },
  plugins: [],
};

export default config;
